### PR TITLE
the navbar overhaul

### LINKED ISSUE #111: Bug: Navbar UI Overlap
There is a bit of a strange issue with the navigation bar having some overlap with the scrollbar. Two images below shows what it normally looks like on other sites and what it looks like on our sites. Found on Chrome.

image

image

### LINKED ISSUE #160: Add [Platform] button to website
Button to visit -> https://platform.acmcyber.com

### PR DESCRIPTION
**Pull request by AVDestroyer**
do we wanna make the navbar buttons narrower or nah?
closes #160 
closes #111

### CODE REVIEW

**Comment by Arc-blroth** [comment]
is it time to make multilevel menu headers :skull:

```
About
+ Members

Events
+ Archive

Blog

Links
+ Platform
+ PBR
+ LA CTF
+ Status
```

**Comment by Arc-blroth** [comment]
also (going to) close #111

**Comment by AVDestroyer** [comment]
On firefox on windows, it has a scroll bar on the bottom.

I do remember this happening to me in 35l and I think the fix was to make the width 99vw instead of 100vw if that's related to this at all.

image

**Comment by AVDestroyer** [comment]
this happens on all my browsers, but only on the landing page

**Pull request merged**
