### PR TITLE
Feat: Initiative Descriptions and Member Page

### LINKED ISSUE #85: feat: Initative Descriptions
One of the primary reasons why people check out our website is to figure out what may be interesting about our club. While we currently have some basic descriptions on our home page, some more in depth descriptions would help improve this. While a few locations are possible, one proposed solution is to separate the members content to its own page, `/members`, and to add the other content to the `/about` page. This would be a helpful page to link people to when trying to read more about what our club does.

### PR DESCRIPTION
**Pull request by ssalandary**
## Summary

Closes #85

Create initiative descriptions and add to "About" Page of site. Move all member-specific content to a dedicated "members" page.

### CODE REVIEW

**Review by bliutech — APPROVED** [review]
LGTM! Let me add @Arc-blroth as a reviewer just to get a second pair of eyes on the styling changes I made.

**Comment by bliutech** [comment]
🤡

**Review by Arc-blroth — COMMENTED** [review]
- we should probably add an image to the members page
- i'm slightly worried about the duplication of the `cyberThing` class across the `Home.module.scss` and `About.module.scss`, but it should be fiiiiiiiine
- benson just reminded me we need to fixup the links in home so lemme do that

**Review by Arc-blroth — APPROVED** [review]
appears satisfactory from my perspective

**Pull request merged**
