### PR TITLE
fixed some styling for blog posts

### PR DESCRIPTION
**Pull request by AVDestroyer**
would like a double-check that there aren't other weird styling things

changes:
- made lists indented
- links have color and underline
- made inline code blocks have a background (not sure if i'm using the right color though)
- added space around top/bottom of images, code blocks, and h3/h4
- increased line spacing to 1.5
Perhaps the h3/h4 elements need to be bigger but I'm not sure

### CODE REVIEW

**Comment by bliutech** [comment]
Two stage review process. First by @renukabhu, second by @Arc-blroth.

**Review by renukabhu — COMMENTED** [review]
The spacing looks good, but i think h3 and h4 elements should be bigger. 

Also, because the links are yellow, the link for projects on the top right are yellow and doesn't show up as well on the pink background. Maybe it would be better to make links pink.

**Review by renukabhu — CHANGES_REQUESTED** [review]
The spacing looks good, but i think h3 and h4 elements should be bigger. 

Also, because the links are yellow, the link for projects on the top right is yellow and doesn't show up as well on the pink background. Maybe it would be better to make links pink.

**Comment by AVDestroyer** [comment]
some more changes that should be made (will do in the following commit)
- indents for lists should use rem and not px
- text sizing is inconsistent

**Review by bliutech — APPROVED** [review]
LGTM!

**Pull request merged**
