### PR TITLE
Add Malware Lab Blog Post

### PR DESCRIPTION
**Pull request by RoryHemmings**
Add Malware Lab Blog Post

## Summary

Copy and pasted blog post from [here](https://github.com/RoryHemmings/cyber-rootkit-s23/blob/main/blog_post.md). Reformatted to match that of previous blog posts.

## Test Plan

If it doesn't show up correctly on the page, I'll PR a change.

### CODE REVIEW

**Comment by RoryHemmings** [comment]
Bump

**Comment by bliutech** [comment]
From what I remember, there is an issue with code blocks rendering at the moment (some sort of weird overflow or clipping if my memory serves me correct). 😓 Will merge once we get a chance to fix that issue. Apologies for the delay.

**Comment by joshuazhu17** [comment]
I'm adding this to the mega-blog-post PR

**Comment by bliutech** [comment]
Reopening because it is a lot simpler to merge this way than block on the other branch.

**Review by bliutech — APPROVED** [review]
Content has been approved for a while. LGTM. Sorry for the delay!

**Pull request merged**
