### PR TITLE
Feat/rererereredesign2

### PR DESCRIPTION
**Pull request by zhamic7**
## Summary

Closes #

### CODE REVIEW

**Review by bliutech — CHANGES_REQUESTED** [review]
Great start! Couple points of feedback.

Spacing looks a bit cramped below. Would this be something that we could adjust? Also, the corresponding height and width for images seems a bit cramped as well.
image

I noticed you opted to use the styling of the events page. Is this there a reason for this? Could I suggest keeping styling separate since I assume similar to the above problem, there may be classes or styles that differ especially spacing wise between the two pages.

**Comment by zhamic7** [comment]
It is more advantageous to uniformize styles in code so we can avoid visual inconsistencies. The problem with image sizing is due to a discrepancy in how events.tsx and archive.tsx size images of arbitrary dimensions-- I will fix that. The archive popup is essentially the event popup with an extra section, so I can just adjust the spacing between old/new sections if the original spacing of the event popup is fine. I don't think either of these problems warrants separate styling.

**Comment by bliutech** [comment]
So I will use `/blog` as a reference point. In terms of those cards, it makes sense to stylize them separately just due to the fact that there is additional content. While these pages are both events, do you think it's worthwhile tying these two together? This may cause issues down the line when trying to stylize things individually. I will let you make the final call on this.

**Comment by bliutech** [comment]
Also, quick suggestion. Are there better SVG assets that are more similar in style to the pure white assets we use on the home page? This may make things fit more in style.

**Comment by zhamic7** [comment]
If we want to drastically change archive/event cards in style, it would be as much work to rewrite some ArchivePopUp.module.scss as it would be to add it. Since we've already decided to use the same card format for now, there's no reason to not maintain concision. Blog cards are inherently different in content, and thus similarities between blog and archive/event cards are negligible in the first place; archived events are derived from events content-wise.

**Comment by zhamic7** [comment]
Revisions of archive page look good. May want to change the font size of "No Recording"/"No Slides" to that of time/location on event cards (i.e. smaller).

**Review by bliutech — APPROVED** [review]
Approved with @zhamic7's feedback!

**Pull request merged**
